export const checkResult = {
  summary: "Checks completed for ['bkr,vgc,threeHours'] of flexkids",
  date: "18-08-2025",
  issues: [],
  references: [
    [
      "0ac41857_2025-week-34(2).png",
      "64375a36_2025-week-34(4).png",
      "6390737c_2025-week-34(3).png",
      "90f489af_2025-week-34(1).png",
    ],
    [
      "5ea99289_18-08-2025(1).png",
      "7abdf4da_22-08-2025.png",
      "68f41ce8_21-08-2025(2).png",
      "59cfdffd_18-08-2025(2).png",
      "522b9294_19-08-2025(2).png",
      "b30edd56_19-08-2025(1).png",
      "1d77c598_20-08-2025(1).png",
      "677a6cdc_21-08-2025(1).png",
      "5649408d_20-08-2025(2).png",
    ],
    ["c5fbe62f_week-34-2025.png"],
    ["b7fd5b2c_vgc_list.json"],
  ],
  status: "ok",
  modules: ["bkr", "vgc", "threeHours"],
  result: [
    "1e523f70-8b03-4977-9901-696f96929955",
    {
      day: "18-08-2025",
      slices: [
        {
          Date: "18-08-2025",
          "From Time": "06:00",
          "To Time": "06:15",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 0,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "06:15",
          "To Time": "06:30",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 0,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "06:30",
          "To Time": "06:45",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 0,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "06:45",
          "To Time": "07:00",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 0,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "07:00",
          "To Time": "07:15",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 0,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "07:15",
          "To Time": "07:30",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 0,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "07:30",
          "To Time": "07:45",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 1,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "07:45",
          "To Time": "08:00",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 1,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "08:00",
          "To Time": "08:15",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 1,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "08:15",
          "To Time": "08:30",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 1,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "08:30",
          "To Time": "08:45",
          "#Children": 9,
          RequiredStaff: 1,
          "#Staff": 1,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "08:45",
          "To Time": "09:00",
          "#Children": 10,
          RequiredStaff: 1,
          "#Staff": 1,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "09:00",
          "To Time": "09:15",
          "#Children": 11,
          RequiredStaff: 1,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "09:15",
          "To Time": "09:30",
          "#Children": 18,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "09:30",
          "To Time": "09:45",
          "#Children": 18,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "09:45",
          "To Time": "10:00",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "10:00",
          "To Time": "10:15",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "10:15",
          "To Time": "10:30",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "10:30",
          "To Time": "10:45",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "10:45",
          "To Time": "11:00",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "11:00",
          "To Time": "11:15",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "11:15",
          "To Time": "11:30",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "11:30",
          "To Time": "11:45",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "11:45",
          "To Time": "12:00",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "12:00",
          "To Time": "12:15",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "12:15",
          "To Time": "12:30",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "12:30",
          "To Time": "12:45",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "12:45",
          "To Time": "13:00",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "13:00",
          "To Time": "13:15",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "13:15",
          "To Time": "13:30",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "13:30",
          "To Time": "13:45",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "13:45",
          "To Time": "14:00",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "14:00",
          "To Time": "14:15",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "14:15",
          "To Time": "14:30",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "14:30",
          "To Time": "14:45",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "14:45",
          "To Time": "15:00",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "15:00",
          "To Time": "15:15",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "15:15",
          "To Time": "15:30",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "15:30",
          "To Time": "15:45",
          "#Children": 20,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "15:45",
          "To Time": "16:00",
          "#Children": 18,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "16:00",
          "To Time": "16:15",
          "#Children": 18,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "16:15",
          "To Time": "16:30",
          "#Children": 18,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "16:30",
          "To Time": "16:45",
          "#Children": 18,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "16:45",
          "To Time": "17:00",
          "#Children": 15,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "17:00",
          "To Time": "17:15",
          "#Children": 15,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: "BKR failed: 1 staff for 15 children (need 2)",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "17:15",
          "To Time": "17:30",
          "#Children": 15,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: "BKR failed: 1 staff for 15 children (need 2)",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "17:30",
          "To Time": "17:45",
          "#Children": 15,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: "BKR failed: 1 staff for 15 children (need 2)",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "17:45",
          "To Time": "18:00",
          "#Children": 15,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: "BKR failed: 1 staff for 15 children (need 2)",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "18:00",
          "To Time": "18:15",
          "#Children": 2,
          RequiredStaff: 1,
          "#Staff": 1,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "18:15",
          "To Time": "18:30",
          "#Children": 2,
          RequiredStaff: 1,
          "#Staff": 1,
          BKR: "Yes",
          VGC: "Yes",
          Details: "",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "18:30",
          "To Time": "18:45",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 0,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
        {
          Date: "18-08-2025",
          "From Time": "18:45",
          "To Time": "19:00",
          "#Children": 0,
          RequiredStaff: 0,
          "#Staff": 0,
          BKR: "Yes",
          VGC: "Yes",
          Details: "No children present",
          "3-UURS": "Yes",
        },
      ],
      three_uurs_summary: {
        "3-UURS": "Yes",
        Reason: "Total deviation 60 minutes within 180 min allowance",
        Deviations: [
          "17:00-17:15 (staff 1/2)",
          "17:15-17:30 (staff 1/2)",
          "17:30-17:45 (staff 1/2)",
          "17:45-18:00 (staff 1/2)",
        ],
      },
    },
  ],
};
