export const checkResult = {
  status: {
    message: "completed",
    progress: 100,
  },
  summary: "Checks completed for ['bkr', 'vgc'] of flexkids",
  date: "20-05-2025",
  issues: [],
  references: [
    ["6bb2cbba_VGZ - Children.pdf"],
    [],
    ["6b2a359a_BKR - Staff.docx"],
    ["923b5121_VGZ-List.docx"],
  ],
  modules: ["bkr", "vgc"],
  result: [
    "b6389b5a-e7ed-4034-96c9-affa5fa541cc",
    {
      day: "20-05-2025",
      slices: [
        {
          Date: "20-05-2025",
          "From Time": "06:00",
          "To Time": "06:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 0,
          BKR: "",
          VGC: "Unknown",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "06:15",
          "To Time": "06:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 0,
          BKR: "",
          VGC: "Unknown",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "06:30",
          "To Time": "06:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 0,
          BKR: "",
          VGC: "Unknown",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "06:45",
          "To Time": "07:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 0,
          BKR: "",
          VGC: "Unknown",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "07:00",
          "To Time": "07:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 0,
          BKR: "",
          VGC: "Unknown",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "07:15",
          "To Time": "07:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 0,
          BKR: "",
          VGC: "Unknown",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "07:30",
          "To Time": "07:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: ["BKR failed: 1 staff for 10 children (need 2)"],
        },
        {
          Date: "20-05-2025",
          "From Time": "07:45",
          "To Time": "08:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: ["BKR failed: 1 staff for 10 children (need 2)"],
        },
        {
          Date: "20-05-2025",
          "From Time": "08:00",
          "To Time": "08:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: ["BKR failed: 1 staff for 10 children (need 2)"],
        },
        {
          Date: "20-05-2025",
          "From Time": "08:15",
          "To Time": "08:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: ["BKR failed: 1 staff for 10 children (need 2)"],
        },
        {
          Date: "20-05-2025",
          "From Time": "08:30",
          "To Time": "08:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: ["BKR failed: 1 staff for 10 children (need 2)"],
        },
        {
          Date: "20-05-2025",
          "From Time": "08:45",
          "To Time": "09:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "Yes",
          Details: ["BKR failed: 1 staff for 10 children (need 2)"],
        },
        {
          Date: "20-05-2025",
          "From Time": "09:00",
          "To Time": "09:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "09:15",
          "To Time": "09:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "09:30",
          "To Time": "09:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "09:45",
          "To Time": "10:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "10:00",
          "To Time": "10:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "10:15",
          "To Time": "10:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "10:30",
          "To Time": "10:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "10:45",
          "To Time": "11:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "11:00",
          "To Time": "11:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "11:15",
          "To Time": "11:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "11:30",
          "To Time": "11:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "11:45",
          "To Time": "12:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "12:00",
          "To Time": "12:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "12:15",
          "To Time": "12:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "12:30",
          "To Time": "12:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "12:45",
          "To Time": "13:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "13:00",
          "To Time": "13:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "13:15",
          "To Time": "13:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "13:30",
          "To Time": "13:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "13:45",
          "To Time": "14:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "14:00",
          "To Time": "14:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "14:15",
          "To Time": "14:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "14:30",
          "To Time": "14:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "14:45",
          "To Time": "15:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "15:00",
          "To Time": "15:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "15:15",
          "To Time": "15:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "15:30",
          "To Time": "15:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "15:45",
          "To Time": "16:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "16:00",
          "To Time": "16:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "16:15",
          "To Time": "16:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "16:30",
          "To Time": "16:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "16:45",
          "To Time": "17:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 2,
          BKR: "Yes",
          VGC: "Yes",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "17:00",
          "To Time": "17:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "No",
          Details: [
            "BKR failed: 1 staff for 10 children (need 2)",
            "Jemima Joren, Amy van Lieshout for Abel Pagliero",
            "Jemima Joren for Dani Brandsma",
            "Jemima Joren, Amy van Lieshout for Ida de Graaf",
          ],
        },
        {
          Date: "20-05-2025",
          "From Time": "17:15",
          "To Time": "17:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "No",
          Details: [
            "BKR failed: 1 staff for 10 children (need 2)",
            "Jemima Joren, Amy van Lieshout for Abel Pagliero",
            "Jemima Joren for Dani Brandsma",
            "Jemima Joren, Amy van Lieshout for Ida de Graaf",
          ],
        },
        {
          Date: "20-05-2025",
          "From Time": "17:30",
          "To Time": "17:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "No",
          Details: [
            "BKR failed: 1 staff for 10 children (need 2)",
            "Jemima Joren, Amy van Lieshout for Abel Pagliero",
            "Jemima Joren for Dani Brandsma",
            "Jemima Joren, Amy van Lieshout for Ida de Graaf",
          ],
        },
        {
          Date: "20-05-2025",
          "From Time": "17:45",
          "To Time": "18:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "No",
          Details: [
            "BKR failed: 1 staff for 10 children (need 2)",
            "Jemima Joren, Amy van Lieshout for Abel Pagliero",
            "Jemima Joren for Dani Brandsma",
            "Jemima Joren, Amy van Lieshout for Ida de Graaf",
          ],
        },
        {
          Date: "20-05-2025",
          "From Time": "18:00",
          "To Time": "18:15",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "No",
          Details: [
            "BKR failed: 1 staff for 10 children (need 2)",
            "Jemima Joren, Amy van Lieshout for Abel Pagliero",
            "Jemima Joren for Dani Brandsma",
            "Jemima Joren, Amy van Lieshout for Ida de Graaf",
          ],
        },
        {
          Date: "20-05-2025",
          "From Time": "18:15",
          "To Time": "18:30",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 1,
          BKR: "No",
          VGC: "No",
          Details: [
            "BKR failed: 1 staff for 10 children (need 2)",
            "Jemima Joren, Amy van Lieshout for Abel Pagliero",
            "Jemima Joren for Dani Brandsma",
            "Jemima Joren, Amy van Lieshout for Ida de Graaf",
          ],
        },
        {
          Date: "20-05-2025",
          "From Time": "18:30",
          "To Time": "18:45",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 0,
          BKR: "",
          VGC: "Unknown",
          Details: [],
        },
        {
          Date: "20-05-2025",
          "From Time": "18:45",
          "To Time": "19:00",
          "#Children": 10,
          RequiredStaff: 2,
          "#Staff": 0,
          BKR: "",
          VGC: "Unknown",
          Details: [],
        },
      ],
    },
  ],
};
